---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-pv
  labels:
    app: spinnaker
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/docker-registry"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-pv-claim
  namespace: spinnaker
  labels:
    app: spinnaker
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: spinnaker
  labels:
    app: spinnaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spinnaker
  template:
    metadata:
      labels:
        app: spinnaker
    spec:
      containers:
      - name: registry
        image: registry:2.6.2
        volumeMounts:
        - name: repo-vol
          mountPath: /var/lib/registry
        - name: certs-vol
          mountPath: "/certs"
          readOnly: true
        - name: auth-vol
          mountPath: "/auth"
          readOnly: true
        env:
        - name: REGISTRY_AUTH
          value: "htpasswd"
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: "Registry Realm"
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: "/auth/htpasswd"
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: "/certs/tls.crt"
        - name: REGISTRY_HTTP_TLS_KEY
          value: "/certs/tls.key"
      volumes:
      - name: repo-vol
        persistentVolumeClaim:
          claimName: docker-pv-claim
      - name: certs-vol
        secret:
          secretName: certs-secret
      - name: auth-vol
        secret:
          secretName: auth-secret
---
apiVersion: v1
kind: Service
metadata:
  name: registry-svc
  namespace: spinnaker
  labels:
    app: spinnaker
spec:
  selector:
    app: spinnaker
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
