---
apiVersion: v1
kind: Namespace
metadata:
  name: spinnaker
spec: {}
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZLRENDQXhDZ0F3SUJBZ0lVWGU1VUNZT0ZSWmdGZ2hyOGdwYnJucWdidi93d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01jbVZuYVhOMGNua3RjM1pqTUI0WERUSXlNREl5TlRBMk5UTXdNRm9YRFRJegpNREl5TlRBMk5UTXdNRm93RnpFVk1CTUdBMVVFQXd3TWNtVm5hWE4wY25rdGMzWmpNSUlDSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FnOEFNSUlDQ2dLQ0FnRUFyZFFxd25WcWVQcnRXcFRjTHNlRFZKeFRnTXJGNC9RQnlMMmMKMXBHNmdsM0IrSElqamxOK3BKd1k5VUNZUmJEMGJnUmdVK2wxWTF6SU5GWXJ4dnNPVUZKQ2hORHpMWmNHbnlnTwplQXRiVUZDdW13MUZqalovdFNpOWpVNG9XZDZzSFhwSWNpejJhbnBYVU1YUnVpSk1KaXdGdmJxc21SaXNCb1pmCnllS0N1K1FzbnRSY1M5NXBLZzRneUg4MkZUQmdZY0thR3U4ZGxqdGo1QzNpa09KTmlhdHZMWW1UN3RIa1hZM2cKU2ZVYitrYXRpNVpleUw4aDlLcEZ6U2ZkZkUwZTJuUHV3TkNRWGVNNU9tditGUXdzcHgybGt0eWJkZHBxd2xSQgpFODFkaVZCTnZDVnJCNmVOVGFsU0FFdzUwSDBzMzI3UWszanl2cTFuQWRFWHV4WHVXL0dBTHErQjFuMEpJM0pDCjBVQkZESWhvMFdYbUFaa3RlaVR2c3pNc3FvRjVYQ1oyWmcyUVFwcHhqZ3N3TDd6d0JLVGJpT1RVdGRieXB6Z3EKR3BGSExzZkhEOEowU0xNaHJNWVpYdjU4VWRxUlI5MU1LUlVDYnJsc1A2Ukw4Q2sybzNCOUdQWU0reHk3czJtbgpaejAwWnVueFFWaUFQcGRJMHdydHY4OW12TVZ3aTVWZnJRMHNLUTFhNXhFWjNTNkxVaWcza0lYZE1WRU5oYnRyCktKZ3FaeGRtQllMRU9MRUZ5V252bTg5RUZCZ2dUVndQbXJVVXl5WWdta0dEbjVMWlMzcVZkQ2lBc01XVWVHNkYKOGVYTU1kbjFObGlDamJzUHdkOEYrOUNEYUlvdXp5NVRxNlBveU1wanFlOHVhSE40cEdmbFFGNFdYNnBoMms4aApWalJTc2xNQ0F3RUFBYU5zTUdvd0hRWURWUjBPQkJZRUZERVB1L2FBeWFZQXNSL3h5Y2FjMzhaZTFtaXlNQjhHCkExVWRJd1FZTUJhQUZERVB1L2FBeWFZQXNSL3h5Y2FjMzhaZTFtaXlNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHcKRndZRFZSMFJCQkF3RG9JTWNtVm5hWE4wY25rdGMzWmpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUNBUUNTa3Jqdgo4NFZoMWd1aWlvRWN4R0pNOXEwWUcxbUNnR1NKZGVIcE1sR2RVb0x5bkdBclprTkIvVit6ZnNtcTRZVy9KcVVoClVvc2lZQjJjUDVZTUFsMDZ3VCt6ZUdMWlFBdS9GZVhzZUQyOVdyYUhyTThBV0JZejZDZjlhU1plQnBTU2xQVUwKNVdRdWJUaUNiVVNSOVJVMzQzZmNrR1Q3RUd1WHgxVytvNFVCMFlJUGlzNmhyUUtsR2pPTXcwNFJrTHlhZFc1WQoyQmVZZEhuMmtUZWdFQ3RiQ09oSngvZVJGTWh1THVjNjVnZnRiMXBaQmJCY3owU3R6bW1QZGtQamZtUVhveC9NCktlSTdmVUhCRm9qTk1QSmcxUzdoZ2FSRVNWRVBYenhtbjlFSEcyYTI1aGs1cisxeGwwR0Z3UEJ0OUF6bWVRRDgKSVV0QkI0RFhtOU53MVdCOW5mR1d4ajBLVk5FVlhjbyt0N0lpSCtZWHZqQkRMYzgwdlRYUVlmRVlQK3BHc1NybQowRXVHNy9GYmlxUGlXVE5ndVR1UDZQZE42cEIySnFlcHBDTHI0MU5tbFRGV1FOaEhaMUZIMUVWdnBaSEUwTVdNCk92UjYzcEMyQmh6WWRUZXJEQ2h1VVFycWd3Z1BpZUQrYXM5Q2J1OVRBNUgzYndxMzk5V1pqZXVBNXpPNmZFamQKVWx0eXlNRkZaMjhMZFo2ejJHWk1xSUY1NHZaOG9kMWk5cEJBK2VFeXVyTkc5cjNVV3FvQjVsM04zQy9hdFZxdApyelFPRnplS2YrWGZwSWw3VjVmQmJCRnVONmMyQ2ZlMnhDdmVwdXNnZXNmWFhHZzYvQnBodGVBN0hVT1FtMjZkCkpqOXpPOEVwSnFQK1JOay9SeUZFa1p2alFRODE0dEZLVTJrVm1BPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQ1N3d2dna29BZ0VBQW9JQ0FRQ3QxQ3JDZFdwNCt1MWEKbE53dXg0TlVuRk9BeXNYajlBSEl2WnpXa2JxQ1hjSDRjaU9PVTM2a25CajFRSmhGc1BSdUJHQlQ2WFZqWE1nMApWaXZHK3c1UVVrS0UwUE10bHdhZktBNTRDMXRRVUs2YkRVV09ObisxS0wyTlRpaFozcXdkZWtoeUxQWnFlbGRRCnhkRzZJa3dtTEFXOXVxeVpHS3dHaGwvSjRvSzc1Q3llMUZ4TDNta3FEaURJZnpZVk1HQmh3cG9hN3gyV08yUGsKTGVLUTRrMkpxMjh0aVpQdTBlUmRqZUJKOVJ2NlJxMkxsbDdJdnlIMHFrWE5KOTE4VFI3YWMrN0EwSkJkNHprNgphLzRWREN5bkhhV1MzSnQxMm1yQ1ZFRVR6VjJKVUUyOEpXc0hwNDFOcVZJQVREblFmU3pmYnRDVGVQSytyV2NCCjBSZTdGZTViOFlBdXI0SFdmUWtqY2tMUlFFVU1pR2pSWmVZQm1TMTZKTyt6TXl5cWdYbGNKblptRFpCQ21uR08KQ3pBdnZQQUVwTnVJNU5TMTF2S25PQ29ha1VjdXg4Y1B3blJJc3lHc3hobGUvbnhSMnBGSDNVd3BGUUp1dVd3LwpwRXZ3S1RhamNIMFk5Z3o3SEx1emFhZG5QVFJtNmZGQldJQStsMGpUQ3UyL3oyYTh4WENMbFYrdERTd3BEVnJuCkVSbmRMb3RTS0RlUWhkMHhVUTJGdTJzb21DcG5GMllGZ3NRNHNRWEphZStiejBRVUdDQk5YQSthdFJUTEppQ2EKUVlPZmt0bExlcFYwS0lDd3haUjRib1h4NWN3eDJmVTJXSUtOdXcvQjN3WDcwSU5vaWk3UExsT3JvK2pJeW1PcAo3eTVvYzNpa1orVkFYaFpmcW1IYVR5RldORkt5VXdJREFRQUJBb0lDQUVpWjBMSWZNRFVQT0lzWW1VM0FibzJzCkxRUWhyTDBrY0lwVEIycG11eXN2MVkvYXZCYjVzRzgzOHdTYjBmMXBodTFjVG84OWRwWGxib2pOWk1OYW9BUFUKRjR3NWFSZWxlRktJL0dJTy9EaHpPam53TlJqTWtsSXJqZCt5d1Erbi9PTGk2OWNrQ0ZjNGViZDJwNzNDRFdQMApCd0hUTWJ0UG5xbXEvZDdvQ0FwSnBvay8wTHl2UytVUXVZaUQrU2FvYWRqcTJrcGRqRkh1eEMzTkxFK3U5UXVHCjJveCtaWmJkZXkvSHplR1Z5ZldpQjJIQmtCendGMUtFdTFxUVIrVmVvSUJFNDNjTXBQOVJvOWxPdVhRNC9YMWUKMklTYU55UGw4YWp3WDYzUm5EdDVtcjMyTXRtamxWVFdYelZZb056L0t2cTI0YzUyT1l5Q0IvK3VRT2NXcGRKNApYeXo4c0F1RVo5SDhhL1NPemFPMzEvSWZIN2VibWRIbUVKS3QwZXNjVlIzVkQxQXhRbWU4cm1OaS8zSDFCbjUyCnRlN2NMb0NpdEFiR1ljcHlCYnloWUR0WTEra3NETnRoWWxHTnFXYWlYTEhneEZEM200M1lEN0k5N09JY2lOS3oKK1FmVE9rbTZtWlRVYWJheFNNTkhDR2xZVmY0MUE0c1BNTy92Q0hpTkNKYnFIbVNBeXducG5yTlNxUXVQS2dwVgp4OEtiOVVUTTJOaG9GQ0NVOG5qS3RlWndyTmRiS0hrblRDc3ZleEdIRFVIU2RNUHd1c0dJT1FrdmtjSnljSzhLCnQ1TC9OQ1BzaXplRWlLM290eTgvYkptWnhEUzBaNHZ4WWVIRTRKNGcxM1dwdkFoYWJYbUlsM2FQQWtjU2NyQjgKY1F2T01semt3VXk1QXZmMFlpVUJBb0lCQVFEZ3E4N2ZKMVlIY1BCeUZENENIMEZUdmxxMCt3QlE2aGo0NmFuZQpCNm9HUkU0YmEwM056K2F0MTZsWFZEdVJud2hwV0tFaEYvUDR6cm9ncVFxYy9XcjJxcFhlSW1HdEUrUlFGS0hTCis0OFdWUXViM2FTWFlnaE5tWm9BM1VtcW1WMStrVnRIWldyNzU0dVNsc01RYjlQY1dpRTRpV0FpY2NHK1BuUXAKeHhFUWtHU2tQQXBuVzk1YlcwSG1aYWloNmQ1NEFzOC84bUhDdGdsK0NLSWtTTnlYbkdPTm5oTnMwSmE5Tkx6TAoxaEIwdDhCQXhGSnQrYjZRSVAvcEthdmR3bDE4V21wQmRZbmljWFdqdWRUWTdFWXN6d1BZNFNlRnJuS1M0bXdkCmhFWVhKN3RPQjZsR1ZmQ3plblV1Y3FtRXpJY2tvNEZqb0xlRHQ5eXU0ZFpsUlFPekFvSUJBUURHRVdwZGF6anQKSUpOVW1Xa09LclZZR01UUUdlUm9ZcTJhU1Y1T2pnRWlOSitESHN4Z0RMM3l3UVlzQ0ZuaVNXN2laVlliRS8ydApBNkNIQlFCYkZ5ayt0MFlrb3JDME45WjREMmt1L2U3ODZ5Q080Mmk3bkdJeWlIRERJSWx6WnJMTlZmMFhNbldPCitMK1loejJ0ODQ2SFFJM1h4SzErei9WNlhPei9xcitGSVE5UGczNXhKTm9DUFFib1h5YUV1TnRhdmF4NXUxMysKMGRmakNKV09jNG16MW4yNFhSbnVXakdxc29yMGpvTzJSay83QmFPVk1ZeVRwNnpSKzVWMzdubWRXYk1DWmhGTApoU05YZFh3L09BOWhCVEVPQ1FwbHYrRlcyOURoUUVhSmEvTkh5NzhkcU0zdWtyaVFkMDExb2dZQVk5TWN2cWM1CldVaFFKN0ozK3NiaEFvSUJBQS81cDNnT24vdGZlSGxrSHhTZmpGR2NFMjhTK2U3RzlvZWNkY3VuMTlzaU9EdVMKNGJGa3V3NVphMTBlVEM0S2xOcUl4c3hIbTcxeFZhTEU0bEJQWksrdGFZS21CelA3V2h5bm11b1pvUThCZFJYYwpLTHZxNkpRNys4dGI4TVVFcXJVNU9MaFc2Y2lIcWxEK0QxaTMydVNzTS9pRkxDVEcyZlBoRlBsemdpOGZWVWlvClRFVVZMelpud3NQVExxNTBwckQ1NGlxMTNXV3U4L1hXUDFFOUxSSkt1SGwxYUFRd3dNY3JYTkZSbzFIcFR1NU0KQjJCeWhhNVI2bUIxNmhhV24zY2NKcm9JMVlrWWNEajRHYjVpN29wNUhkanFDWmxqMGhuSHA5QmhlMnBpRk50egppQUhNVXBVd2UreVZrcUF5dXRsTUZ3TXlobG9EVk5uS2pTZ2VSQ2tDZ2dFQU4rcld3b1R3ejFFeEJ1TkFtM1ZICk9SWFZDb01renF0OUkxK3ZOakkwODdremgwcjhtK2s4L3ZtcmltYlpLVjlkNUtDRFRLVzZLa3dwMTdSN3d6dW8KczBIK2xYMHdzZEJKeGg5anJKYVlEK001ajkxM3hlK0NjWTIvZC9jSmx3RFpYY3IyNXNPaUdMajFMbFNQL3pvUgpkUEd1bWNtMnlXUmdneWtVNTZFRzdNakdqOFlwdmp1UEtLNmQ4cUJhT1lJT3UzRnM3ZmtOc2xEL3grSzJoajdzCkUwOXNzczNsOGpxWVp2NTg2RW9MdVR2a2ZKTzgrUFBDSWpWbVB1bnQ2cXZ5dlkrRFVCd01xZXR1Yk5TSVBUalEKYnEyT2ljM1hsNTR5T2RsWkFSNnFTMFdrcXhKRVpGVXh2amJCMEZjK0VRV3ErQlUybHBqa2tQWTV5aGRLOVVCaApRUUtDQVFFQWhWTjlkSDZTSHd0YlA2cS9nVEJjTGVLWUJaQjk0MEl3Z0JDUDRzeGI4ZklaY3VUTGsrK281MkR5Clp5YWo3MVdCT3BUMXM5SWlOeFlHUmZwMm1RcmsxeU94a0pDSkh0b0pyNHZUK3RNblhDZGlHSDd3TVpJWTVtWVkKdVF1UGpQdExKUm4zM05RcFc5b0tTUjhxZ2F5aElNd0g2dXIwMmljQTYxWkMydUdZaktrQmFiZ0h1YVMxOTh4Uwoxait6SUcyNkhFZzZqMU1oVWFKWnR2SHpiSjhEbCtvYkd2RXhjcWZhS2N4VHllZnhoUk5aVWUxZHlLREh6QkhLCkgzQVV3KzdNaVhUcGFnTzlvMmlSSkppUVk2RSsyMEpZaXBGRmVLVm9oRitlSEZLcmtpRDY0ZEZYVzlscGN6bXMKYXdNVzViT1ptYVJHaDFFUC9MQmZkRkV1eG1MK0NnPT0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  name: certs-secret
  namespace: spinnaker
type: kubernetes.io/tls
---
apiVersion: v1
data:
  htpasswd: bXl1c2VyOiQyeSQwNSRxdGJmREhSTHgyZjBoZ00vL1p3MGEuT21WOXk1aEFzUHprOVA0djJZNUNhd3F4TGxGQ3pYYQoK
kind: Secret
metadata:
  name: auth-secret
  namespace: spinnaker
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-pv
  labels:
    app: spinnaker
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/docker-registry"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-pv-claim
  namespace: spinnaker
  labels:
    app: spinnaker
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: spinnaker
  labels:
    app: spinnaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spinnaker
  template:
    metadata:
      labels:
        app: spinnaker
    spec:
      containers:
      - name: registry
        image: registry:2.6.2
        volumeMounts:
        - name: repo-vol
          mountPath: /var/lib/registry
        - name: certs-vol
          mountPath: "/certs"
          readOnly: true
        - name: auth-vol
          mountPath: "/auth"
          readOnly: true
        env:
        - name: REGISTRY_AUTH
          value: "htpasswd"
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: "Registry Realm"
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: "/auth/htpasswd"
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: "/certs/tls.crt"
        - name: REGISTRY_HTTP_TLS_KEY
          value: "/certs/tls.key"
      volumes:
      - name: repo-vol
        persistentVolumeClaim:
          claimName: docker-pv-claim
      - name: certs-vol
        secret:
          secretName: certs-secret
      - name: auth-vol
        secret:
          secretName: auth-secret
---
apiVersion: v1
kind: Service
metadata:
  name: registry-svc
  namespace: spinnaker
  labels:
    app: spinnaker
spec:
  selector:
    app: spinnaker
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
